# Git
alias gi="git init"
alias gs="git status"
alias gd="git diff"
alias gdh="git diff HEAD"
alias gc="git clone $1 $2"
alias gcm="git commit -m $1"
alias gaa="git add -A ."
alias gpo="git push origin $1"
alias gll="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gl="git pull"
alias gb="git branch"
alias glrh="git ls-remote --heads"
alias glo="git log --oneline"
alias grhh="git reset --hard HEAD"
alias grh="git reset --hard"
alias gfo="git fetch origin"
alias gcp="git cherry-pick $1"
alias ga="git add $1"
alias gss="git stash save"
alias gsp="git stash pop"
alias gpof="git push origin $1 --force-with-lease"

# Files
alias l="ls -o -hX --group-directories-first"
alias la="ls -o -AhX --group-directories-first"
alias v="nvim"
alias zh="nvim ~/.zsh_history"
alias dot="cd ~/.dotfiles-wsl-v2"

# Npm
alias ni="npm install"
alias nis="npm i -S "
alias nig="npm i -g "
alias nid="npm i -D "
alias nr="npm run $1"
alias nrs="npm run start"
alias nrb="npm run build"
alias nrt="npm run test"
alias nrc="npm run commit"

# Ubuntu package manager
alias sau="sudo apt update"
alias sauu="sudo apt upgrade"
alias sai="sudo apt install"
